### ISSUE TITLE
Game start error

### ISSUE THREAD

**Issue by UrbanSide** [yivry/chained-science#1]
![image](https://github.com/yivry/chained-science/assets/26259129/54195d60-9727-4725-b746-0450fec95e91)

**Comment by dmvdbrugge** [comment]
Fixed in 0.1.1 now available on the portal.

Issue was function `table_contains` was only present in [Chained Recipes](https://github.com/yivry/chained-recipes) but not in Chained Science, which never showed for me as I've apparently never run Chained Science solo 😳

Thanks for the report, apologies for the slow response.
